/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GroundSchoolRouteImport } from './routes/ground-school'
import { Route as FlyingTrainingRouteImport } from './routes/flying-training'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AelpRouteImport } from './routes/aelp'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const GroundSchoolRoute = GroundSchoolRouteImport.update({
  id: '/ground-school',
  path: '/ground-school',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyingTrainingRoute = FlyingTrainingRouteImport.update({
  id: '/flying-training',
  path: '/flying-training',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AelpRoute = AelpRouteImport.update({
  id: '/aelp',
  path: '/aelp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/aelp': typeof AelpRoute
  '/contact': typeof ContactRoute
  '/flying-training': typeof FlyingTrainingRoute
  '/ground-school': typeof GroundSchoolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/aelp': typeof AelpRoute
  '/contact': typeof ContactRoute
  '/flying-training': typeof FlyingTrainingRoute
  '/ground-school': typeof GroundSchoolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/aelp': typeof AelpRoute
  '/contact': typeof ContactRoute
  '/flying-training': typeof FlyingTrainingRoute
  '/ground-school': typeof GroundSchoolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/aelp'
    | '/contact'
    | '/flying-training'
    | '/ground-school'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/aelp'
    | '/contact'
    | '/flying-training'
    | '/ground-school'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/aelp'
    | '/contact'
    | '/flying-training'
    | '/ground-school'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AelpRoute: typeof AelpRoute
  ContactRoute: typeof ContactRoute
  FlyingTrainingRoute: typeof FlyingTrainingRoute
  GroundSchoolRoute: typeof GroundSchoolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ground-school': {
      id: '/ground-school'
      path: '/ground-school'
      fullPath: '/ground-school'
      preLoaderRoute: typeof GroundSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flying-training': {
      id: '/flying-training'
      path: '/flying-training'
      fullPath: '/flying-training'
      preLoaderRoute: typeof FlyingTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aelp': {
      id: '/aelp'
      path: '/aelp'
      fullPath: '/aelp'
      preLoaderRoute: typeof AelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  AelpRoute: AelpRoute,
  ContactRoute: ContactRoute,
  FlyingTrainingRoute: FlyingTrainingRoute,
  GroundSchoolRoute: GroundSchoolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
